# Generated by Django 4.2 on 2023-04-07 06:55

from django.contrib.auth import models as auth_models
from django.db import migrations

from posts import models


def create_writer_user_group(apps, schema_editor):
    group, _ = auth_models.Group.objects.get_or_create(name='writer')

    content_type = auth_models.ContentType.objects.get_for_model(models.Post)

    add_post_permission, _ = auth_models.Permission.objects.get_or_create(codename='add_post',
                                                                          content_type=content_type)
    change_post_permission, _ = auth_models.Permission.objects.get_or_create(codename='change_post',
                                                                             content_type=content_type)
    delete_post_permission, _ = auth_models.Permission.objects.get_or_create(codename='delete_post',
                                                                             content_type=content_type)

    group.permissions.add(add_post_permission, change_post_permission, delete_post_permission)


def reverse_create_writer_user_group(apps, schema_editor):
    auth_models.Group.objects.filter(name='writer').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_writer_user_group, reverse_create_writer_user_group)
    ]
